# Generated by Django 6.0.6 on 2026-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT', 'Tether USDT'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], max_length=10, unique=True)),
                ('network', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet_qr/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
        migrations.AddField(
            model_name='investment',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
